services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pokedex_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - pokedex-network
    volumes:
      # Mapeia a pasta local para dentro do container para não perder o .db
      - ../data:/app/data 

  redis:
    image: redis:7-alpine
    container_name: pokedex_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pokedex-network
    volumes:
      - redis_data:/data

networks:
  pokedex-network:
    driver: bridge

volumes:
  redis_data:
