name: Pokedex API CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    # Sobe o Redis para os testes não quebrarem
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13" 

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.3.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Run Tests with Coverage
      # 👈 ADICIONADO: Variável de ambiente para o código achar o Redis do GitHub
      env:
        REDIS_URL: redis://localhost:6379
      run: poetry run pytest --cov=app tests/

  deploy-render:
      needs: test-and-lint
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      
      steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}